services:
  feedback-analytics-consumer:
    image: maven:3.9.11-eclipse-temurin-25-alpine
    ports:
      - "8081:8081"
    volumes:
      - .:/app
      - maven-cache:/root/.m2
    working_dir: /app
    command: mvn clean package spring-boot:run
    networks:
      - stanjgcnet
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8081/actuator/health"]
      interval: 5s
      timeout: 5s
      retries: 30

volumes:
  maven-cache:




